DROP TABLE IF EXISTS STUDENT_TBL;

CREATE TABLE PRODUCT_TBL (
  studentId INT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  college VARCHAR(250) NOT NULL,
  rollNo VARCHAR(250) NOT NULL,
  course INT NOT NULL,
);